spring.application.name=spring-crud-generator-it-mongo-app
spring.data.mongodb.database=itmongo
de.flapdoodle.mongodb.embedded.version=8.0.3
mongock.migration-scan-package=com.example.itmongo.migration
mongock.enabled=true
